<?php
session_start();
require "../config/config.php";

// Generate a token and store it in DB
$token = bin2hex(random_bytes(16));
$expires_at = date("Y-m-d H:i:s", strtotime("+5 minutes"));

$insert = $conn->prepare("INSERT INTO login_tokens (token, expires_at, is_used, user_id) VALUES (:token, :expires_at, 0, NULL)");
$insert->execute([
    ":token" => $token,
    ":expires_at" => $expires_at
]);
?>

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>Login with QR Code</title>
</head>
<body>
  <h1>Scan this QR code with your logged-in device to approve login</h1>
  
  <!-- Show the QR code image generated by scan-login.php -->
  <img src="scan-login.php?token=<?php echo $token; ?>" alt="QR Code" />

  <script>
    const token = "<?php echo $token; ?>";

    // Poll every 3 seconds to check if QR login was approved
    const checkStatus = () => {
      fetch(`<?php echo APPURL; ?>/auth/check-qr-status.php?token=${token}`)
        .then(res => res.json())
        .then(data => {
          if (data.status === 'approved') {
            alert('Login approved! Redirecting...');
            window.location.href = "<?php echo APPURL; ?>";  // Redirect to homepage or dashboard
          }
        })
        .catch(err => console.error(err));
    };

    setInterval(checkStatus, 3000);
  </script>
</body>
</html>
