on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: 📂 Sync files
      uses: Penguibird/FTP-Deploy-Action@4.2.0
      with:
        server: ftp.maisreyneang.com
        username:  sreyneang@maisreyneang.com
        password: 7?b(CPg8F7Qe
